Repository SOPKATHON-GROUP11/Nangman-Server, pull requests merged in 2022-05, with the labels that each got.

#10 Feature/1
  src/interfaces/fruit/FruitInfo.ts
  src/interfaces/user/UserInfo.ts
  src/model/Fruit.ts
  src/model/User.ts
Labels: ✨ Feature, 🐷 정훈 🐷, 🐼 혁준 🐼

#11 Feature/2
  src/controllers/FruitController.ts
  src/controllers/index.ts
  src/interfaces/fruit/FruitResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/FruitRouter.ts
  src/routes/index.ts
  src/services/FruitService.ts
  src/services/index.ts
Labels: ✨ Feature, 🐼 혁준 🐼

#12 Feature/5
  src/controllers/FruitController.ts
  src/controllers/index.ts
  src/modules/responseMessage.ts
  src/routes/FruitRouter.ts
  src/services/FruitService.ts
Labels: ✨ Feature, 🐷 정훈 🐷

#13 [FEAT] add GET my/check
  src/controllers/MyController.ts
  src/controllers/index.ts
  src/interfaces/my/MyCheckResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/MyRouter.ts
  src/routes/index.ts
  src/services/MyService.ts
  src/services/index.ts
Labels: ✨ Feature, 🐼 혁준 🐼

#14 Feature/7
  src/controllers/FruitController.ts
  src/interfaces/fruit/FruitMyResponseDto.ts
  src/modules/responseMessage.ts
  src/routes/FruitRouter.ts
  src/services/FruitService.ts
Labels: ✨ Feature, 🐷 정훈 🐷

#15 Branch/6
  src/controllers/FruitController.ts
  src/modules/responseMessage.ts
  src/routes/FruitRouter.ts
  src/services/FruitService.ts
Labels: ✨ Feature, 🐼 혁준 🐼

#16 [FEAT] add my/basket api
  src/controllers/MyController.ts
  src/modules/responseMessage.ts
  src/routes/MyRouter.ts
  src/services/MyService.ts
Labels: ✨ Feature, 🐷 정훈 🐷

#17 Branch/3
  src/controllers/FruitController.ts
  src/interfaces/fruit/FruitCreateDto.ts
  src/modules/responseMessage.ts
  src/routes/FruitRouter.ts
  src/services/FruitService.ts
Labels: ✨ Feature, 🐼 혁준 🐼

#18 Feature/4
  src/controllers/FruitController.ts
  src/modules/responseMessage.ts
  src/routes/FruitRouter.ts
  src/services/FruitService.ts
Labels: ✨ Feature, 🐷 정훈 🐷
